### ISSUE TITLE
Blank page when hosted online

### ISSUE THREAD

**Issue by idesignsng** [PunitGr/QuickBill#12]
It works perfectly on my laptop's local server but displays a blank page online. Please how can I fix this

**Comment by PunitGr** [comment]
It seems to me an issue with routing. How are you deploying it?

**Comment by idesignsng** [comment]
I uploaded it to my website file manager in a subfolder named invoice. So
the url is like mydomain.com/invoice

Also I'm on a shared hosting if that helps

**Comment by PunitGr** [comment]
@idesignsng I don't think that will work, since the path is being set by `react-router`. What error do you see on console?

**Comment by idesignsng** [comment]
Oh okay. I guess I'll host in on github instead

**Comment by idesignsng** [comment]
> @idesignsng I don't think that will work, since the path is being set by `react-router`. What error do you see on console?

Hello, I am trying to host it on github but it still displays a blank page
https://idesignsng.github.io/Invoice/

What do i do please

**Comment by PunitGr** [comment]
Quick question: Did you rename the project to Invoice?
If yes, then you'd need to update the routes since the default route is `/Quickbill`
You'll need to update `App.js` and replace `Quickbill` there with `Invoice`.

**Comment by idesignsng** [comment]
I renamed the project back to Quickbill but it's still blank

https://idesignsng.github.io/Quickbill/

**Comment by PunitGr** [comment]
You are using the wrong route.
It is working on: https://idesignsng.github.io/QuickBill/

**Comment by idesignsng** [comment]
Yes, it does now. I have now added a custom subdomain to it https://invoice.awamart.com.ng/

What should be my route in App.js please
