### ISSUE TITLE
What should be my route in App.js please

### ISSUE THREAD

**Issue by idesignsng** [PunitGr/QuickBill#13]
What should be my route in App.js please? I've added a custom subdomain to my github pages

**Comment by PunitGr** [comment]
It should be updated here: https://github.com/PunitGr/QuickBill/blob/master/app/components/App.js
Since you want `/` to be your home page instead of `/QuickBill`, then I'd just say remove `QuickBill` from `App.js`.

```javascript
<Route exact path="/" component={HomePage} />
<Route path="/dashboard" component={Dashboard} />
<Route path="/preview" component={Preview}></Route>
```
