### ISSUE TITLE
Missing count of Fork and Star

### ISSUE THREAD

**Issue by IshaTr** [PunitGr/QuickBill#3]
Your Fork and Star count feature is not visible at the home page in their respective buttons. Would you mind if I can have a  look onto this?
![selection_004](https://user-images.githubusercontent.com/16881750/30805939-5bcf8652-a211-11e7-80cf-15fb7bf99b0c.png)

**Comment by PunitGr** [comment]
Yes sure. PR would be great.

**Comment by IshaTr** [comment]
@PunitGr I have added a PR. Please look into it.
Thanks!

**Comment by PunitGr** [comment]
@IshaTr Looks good to me.
