### ISSUE TITLE
Feature Request - VAT (Value added tax)

### ISSUE THREAD

**Issue by PunitGr** [PunitGr/QuickBill#5]
Add a new feature in invoice settings for value-added taxes `VAT`.

The feature is similar to `Paid to date` i.e. it will have a toggle input to add `VAT`.

Ex. 
![screen shot 2017-09-26 at 1 30 59 am](https://user-images.githubusercontent.com/9111111/30828176-728c06e2-a25a-11e7-8c44-770f2ad7374f.png)

The value of `VAT` will be evaluated in `percentage (%)`.

**Comment by IshaTr** [comment]
Hi,
I would like to work on the addition of this new feature.
