### ISSUE TITLE
When you have more than one Row you can't set prices on both.

### ISSUE THREAD

**Issue by elamhut** [PunitGr/QuickBill#9]
If you click "Add Row" and try to set prices like if I sold you an apple and an orange, I can only set the apple price. When you try to set the orange price either you can't set the numbers or you can set the number but the "Subamount" column won't be updated and won't sum up to the total.

Also the add rows button freaks out and stops working after triggering this bug.

**Comment by PunitGr** [comment]
@elamhut Thanks for pointing it out. Will look into this. 👍

**Comment by PunitGr** [comment]
Fixed [#9](https://github.com/PunitGr/QuickBill/commit/b2746b60abddf36f0bf07c5018de0dc2c014e7f0)
